blueprint:
  name: Play Spotify Podcast on Light Turn On
  description: Automatically play the newest episode of a Spotify podcast when a specific light is turned on
  domain: automation
  input:
    time_start:
      name: Start Time
      description: Time when the automation should start being active
      default: "06:00:00"
      selector:
        time: {}

    time_end:
      name: End Time
      description: Time when the automation should stop being active
      default: "09:00:00"
      selector:
        time: {}
    
    light_entity:
      name: Light
      description: The light that triggers the automation when turned on
      selector:
        entity:
          domain: light
          multiple: false
    
    media_player:
      name: Media Player
      description: The Spotify-connected media player to play the podcast on
      selector:
        entity:
          domain: media_player
          multiple: false
    
    spotify_show_url:
      name: Spotify Show URL
      description: The Spotify show URL (e.g., https://open.spotify.com/show/2yltdfmAGQsU8UnsTBjWwV)
      default: "https://open.spotify.com/show/2yltdfmAGQsU8UnsTBjWwV"
      selector:
        text: {} 
    
    volume_level:
      name: Volume Level
      description: Set the volume level for playback (optional)
      default: 0.5
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.05
          mode: slider

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input light_entity
    to: "on"

condition:
  - condition: time
    after: !input time_start
    before: !input time_end

action:
  - action: media_player.volume_set
    target:
      entity_id: !input media_player
    data:
      volume_level: !input volume_level
  
  - action: media_player.play_media
    target:
      entity_id: !input media_player
    data:
      media_content_type: show
      media_content_id: !input spotify_show_url
